name: objd_gui
description: This is an objD extension for a customizable gui
version: 0.0.1
homepage: https://www.stevertus.com/tools/gui

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  objd: 0.3.3-beta.1
  meta:

dev_dependencies:
  pedantic: ^1.9.0