name: objd_gui
description: This is an objD extension for a customizable gui
version: 0.0.1-beta.1
homepage: https://stevertus.com/tools/gui

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  objd:
    path: C:\dev\Dart\objectiveD
  meta:

dev_dependencies:
  pedantic: ^1.9.0
